language: php

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

branches:
  only:
    - master
    - 9.4.x
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@evoweb.de

# This is executed for all stages
before_install:
  -

install:
  - export TYPO3_PATH_WEB=$PWD/.Build/Web;
  - |
    composer require typo3/cms-core="$TYPO3_VERSION" $PREFER_LOWEST;
    if [ ! -z "$TESTING_FRAMEWORK" ]; then composer require --dev typo3/testing-framework="$TESTING_FRAMEWORK"; fi;
  - git checkout composer.json;
  - ls -la .Build/;
  - ls -la .Build/Web/;

before_script:
  - phpenv config-rm xdebug.ini

script:
  - >
    echo "Running ${TYPO3_VERSION} unit tests";
    php .Build/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/${UNIT_TESTING_FOLDER}/;
    echo "Running ${TYPO3_VERSION} functional tests";
    export typo3DatabaseDriver="pdo_sqlite";
    php .Build/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml Tests/${FUNCTIONAL_TESTING_FOLDER}/;

jobs:
  allow_failures:
    - env: TYPO3_VERSION="dev-master as 10.0.0" TESTING_FRAMEWORK="~5.0.11"

  include:
    - stage: test
      php: 7.2
      env: TASK="XML Lint (Xliff)"
      before_install: skip
      install: skip
      before_script: skip
      script:
        - echo "Running xmllint (Xliff)";
          find Resources/Private/Language/ -name '*.xlf' -type f | xargs xmllint --noout --schema Tests/Fixtures/xliff-core-1.2-strict.xsd

    - &lint
      stage: test
      php: 7.3
      env: TASK="PHP Lint"
      before_install: skip
      install: skip
      before_script: skip
      script:
        - echo "Running php lint";
          errors=$(find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"
    - <<: *lint
      php: 7.2

    - stage: test
      php: 7.3
      env: TYPO3_VERSION="^9.5.0" TESTING_FRAMEWORK="~4.10.0" UNIT_TESTING_FOLDER="Unit9" FUNCTIONAL_TESTING_FOLDER="Functional9"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^9.5.0" TESTING_FRAMEWORK="~4.10.0" UNIT_TESTING_FOLDER="Unit9" FUNCTIONAL_TESTING_FOLDER="Functional9"
    - stage: test
      php: 7.3
      env: TYPO3_VERSION="^10.1.0" TESTING_FRAMEWORK="~5.0.16" UNIT_TESTING_FOLDER="Unit" FUNCTIONAL_TESTING_FOLDER="Functional"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^10.1.0" TESTING_FRAMEWORK="~5.0.16" UNIT_TESTING_FOLDER="Unit" FUNCTIONAL_TESTING_FOLDER="Functional"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master as 10.0.0" TESTING_FRAMEWORK="~5.0.11" UNIT_TESTING_FOLDER="Unit" FUNCTIONAL_TESTING_FOLDER="Functional"

    - stage: publish in ter
      if: tag IS present
      php: 7.2
      before_install: skip
      install: skip
      script:
        - |
          if [[ "$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";

            # Install requirements
            composer global require helhum/ter-client

            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Set version number from tag
            sed -i "s/version' => '.*'/version' => '${TRAVIS_TAG}'/" ext_emconf.php

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload sf_register . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
