language: php

sudo: required

addons:
  apt:
    packages:
      - libxml2-utils

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@evoweb.de

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y

install:
  - >
    export TYPO3_PATH_WEB=$PWD/.Build/Web;
    composer require typo3/minimal="$TYPO3_VERSION" $PREFER_LOWEST;
    composer require --dev typo3/testing-framework="$TESTING_FRAMEWORK";
    git checkout composer.json;

before_script:
  - phpenv config-rm xdebug.ini
  - pecl install libsodium

script:
  - >
    echo "Running ${TYPO3_VERSION} unit tests";
    php .Build/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit/;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export typo3DatabaseDriver="pdo_sqlite";
    php .Build/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml Tests/Functional/;

jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master" TESTING_FRAMEWORK="~5.0.3"

  include:
    - &lint
      stage: test
      php: 7.2
      env: PHP Lint
      before_install: skip
      install: skip
      before_script: skip
      script:
        - errors=$(find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"

    - stage: test
      php: 7.2
      env: Xliff Lint
      before_install: skip
      install: skip
      before_script: skip
      script:
        - echo "Running xmllint (Xliff)";
          find Resources/Private/Language/ -name '*.xlf' -type f | xargs xmllint --noout --schema Tests/Fixtures/xliff-core-1.2-strict.xsd

    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^9.5" TESTING_FRAMEWORK="~4.10.0"

    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master" TESTING_FRAMEWORK="~5.0.3"

    - stage: publish in ter
      if: tag IS present
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";

            # Install requirements
            composer global require helhum/ter-client dev-master

            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Set version number from tag
            sed -i "s/version' => '.*'/version' => '${TRAVIS_TAG}'/" ext_emconf.php

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload sf_register . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
