# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\SfRegister\:
    resource: '../Classes/*'

  Evoweb\SfRegister\Services\Setup\CheckFactory:
    arguments:
      $configuration:
        checks:
            - Evoweb\SfRegister\Services\Setup\UserGroupCheck
            - Evoweb\SfRegister\Services\Setup\UsernameCheck
    public: true

  Evoweb\SfRegister\Command\CleanupCommand:
    tags:
      - { name: 'console.command', command: 'sfregister:cleanup', schedulable: false }

  Evoweb\SfRegister\EventListener\FeuserControllerListener:
    tags:
      - name: event.listener
        identifier: 'sfregister_feusercontroller_processinitializeaction'
        method: 'onProcessInitializeActionEvent'
        event: Evoweb\SfRegister\Controller\Event\ProcessInitializeActionEvent

  Evoweb\SfRegister\Services\Captcha\SrFreecapAdapter:
    public: true
